/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telasa3;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author tanig
 */
public class TelaLaboratorio_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLaboratorio_Cadastro
     */
    public TelaLaboratorio_Cadastro() {
        initComponents();
    }
    
     public TelaLaboratorio_Cadastro(String id, String nome, String tipoAcesso) {
        initComponents();
    jLabelIDHide.setText(id);
        jLabelNome1.setText(nome);
        jLabelTipoAcesso.setText(tipoAcesso);
        jPanelInfoHide.setVisible(false);

        visibilidadeMenu();
    }

    public void visibilidadeMenu() {
        if (jLabelTipoAcesso.getText().equals("Paciente")) {
            tab2.setVisible(true);
            tab2.setVisible(false);
            tab3.setVisible(false);
            tab4.setVisible(false);
        } else if (jLabelTipoAcesso.getText().equals("Medico")) {
            tab2.setVisible(true);
            tab2.setVisible(true);
            tab3.setVisible(false);
            tab4.setVisible(false);
        } else if (jLabelTipoAcesso.getText().equals("Laboratorio")) {
            tab2.setVisible(true);
            tab2.setVisible(true);
            tab3.setVisible(false);
            tab4.setVisible(false);
        } else {
            tab2.setVisible(true);
            tab2.setVisible(true);
            tab3.setVisible(true);
            tab4.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeral = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        jPanelPrimeiraFileira = new javax.swing.JPanel();
        jPanelNome = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jPanelCNPJ = new javax.swing.JPanel();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jLabelCNPJ = new javax.swing.JLabel();
        jPanelTelefone = new javax.swing.JPanel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jPanelTerceiraFileira = new javax.swing.JPanel();
        jPanelRua = new javax.swing.JPanel();
        jTextRua = new javax.swing.JTextField();
        jPanelBairro = new javax.swing.JPanel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        jPanelNumero = new javax.swing.JPanel();
        jFormattedTextFieldNumero = new javax.swing.JFormattedTextField();
        jLabelNumero = new javax.swing.JLabel();
        jLabelSearchPacienteIcon = new javax.swing.JButton();
        jPanelQuartaFileira = new javax.swing.JPanel();
        jPanelEmail = new javax.swing.JPanel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jPanelSenha = new javax.swing.JPanel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jPanelSegundaFileira = new javax.swing.JPanel();
        jPanelCEP = new javax.swing.JPanel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelCEP = new javax.swing.JLabel();
        jPanelEstado = new javax.swing.JPanel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanelMunicipio = new javax.swing.JPanel();
        jTextFieldMunicipio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelTipoAcesso = new javax.swing.JLabel();
        jPanelInfoHide = new javax.swing.JPanel();
        jLabelIDHide = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tab5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeral.setBackground(new java.awt.Color(185, 244, 115));

        jPanelForm.setBackground(new java.awt.Color(185, 244, 115));
        jPanelForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        jPanelPrimeiraFileira.setBackground(new java.awt.Color(185, 244, 115));
        jPanelPrimeiraFileira.setPreferredSize(new java.awt.Dimension(1440, 104));

        jPanelNome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jPanelNome.setPreferredSize(new java.awt.Dimension(226, 24));
        jPanelNome.setVerifyInputWhenFocusTarget(false);

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome.setBorder(null);

        javax.swing.GroupLayout jPanelNomeLayout = new javax.swing.GroupLayout(jPanelNome);
        jPanelNome.setLayout(jPanelNomeLayout);
        jPanelNomeLayout.setHorizontalGroup(
            jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        jPanelNomeLayout.setVerticalGroup(
            jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNome)
        );

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome Fantasia*");

        jPanelCNPJ.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCNPJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jFormattedTextFieldCNPJ.setBorder(null);
        try {
            jFormattedTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldCNPJ.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelCNPJLayout = new javax.swing.GroupLayout(jPanelCNPJ);
        jPanelCNPJ.setLayout(jPanelCNPJLayout);
        jPanelCNPJLayout.setHorizontalGroup(
            jPanelCNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        jPanelCNPJLayout.setVerticalGroup(
            jPanelCNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldCNPJ)
        );

        jLabelCNPJ.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCNPJ.setText("CNPJ*");

        jPanelTelefone.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jPanelTelefone.setPreferredSize(new java.awt.Dimension(226, 24));

        jFormattedTextFieldTelefone.setBorder(null);
        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelTelefoneLayout = new javax.swing.GroupLayout(jPanelTelefone);
        jPanelTelefone.setLayout(jPanelTelefoneLayout);
        jPanelTelefoneLayout.setHorizontalGroup(
            jPanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelTelefoneLayout.setVerticalGroup(
            jPanelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabelTelefone.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone");

        javax.swing.GroupLayout jPanelPrimeiraFileiraLayout = new javax.swing.GroupLayout(jPanelPrimeiraFileira);
        jPanelPrimeiraFileira.setLayout(jPanelPrimeiraFileiraLayout);
        jPanelPrimeiraFileiraLayout.setHorizontalGroup(
            jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimeiraFileiraLayout.createSequentialGroup()
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrimeiraFileiraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNome)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCNPJ))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrimeiraFileiraLayout.setVerticalGroup(
            jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrimeiraFileiraLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelCNPJ)
                    .addComponent(jLabelTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jPanelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelTerceiraFileira.setBackground(new java.awt.Color(185, 244, 115));
        jPanelTerceiraFileira.setPreferredSize(new java.awt.Dimension(1440, 104));

        jPanelRua.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextRua.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextRua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextRua.setBorder(null);

        javax.swing.GroupLayout jPanelRuaLayout = new javax.swing.GroupLayout(jPanelRua);
        jPanelRua.setLayout(jPanelRuaLayout);
        jPanelRuaLayout.setHorizontalGroup(
            jPanelRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextRua, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jPanelRuaLayout.setVerticalGroup(
            jPanelRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextRua, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPanelBairro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBairro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldBairro.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldBairro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBairro.setBorder(null);

        javax.swing.GroupLayout jPanelBairroLayout = new javax.swing.GroupLayout(jPanelBairro);
        jPanelBairro.setLayout(jPanelBairroLayout);
        jPanelBairroLayout.setHorizontalGroup(
            jPanelBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelBairroLayout.setVerticalGroup(
            jPanelBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabelBairro.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairro.setText("Bairro");

        jLabelRua.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelRua.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRua.setText("Rua");

        jPanelNumero.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNumero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jFormattedTextFieldNumero.setBorder(null);
        jFormattedTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextFieldNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldNumero.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelNumeroLayout = new javax.swing.GroupLayout(jPanelNumero);
        jPanelNumero.setLayout(jPanelNumeroLayout);
        jPanelNumeroLayout.setHorizontalGroup(
            jPanelNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelNumeroLayout.setVerticalGroup(
            jPanelNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldNumero)
        );

        jLabelNumero.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Número");

        javax.swing.GroupLayout jPanelTerceiraFileiraLayout = new javax.swing.GroupLayout(jPanelTerceiraFileira);
        jPanelTerceiraFileira.setLayout(jPanelTerceiraFileiraLayout);
        jPanelTerceiraFileiraLayout.setHorizontalGroup(
            jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTerceiraFileiraLayout.createSequentialGroup()
                .addGroup(jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTerceiraFileiraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelBairro)))
                .addGap(18, 18, 18)
                .addGroup(jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRua))
                .addGap(18, 18, 18)
                .addGroup(jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero)
                    .addComponent(jPanelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelTerceiraFileiraLayout.setVerticalGroup(
            jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTerceiraFileiraLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTerceiraFileiraLayout.createSequentialGroup()
                        .addComponent(jLabelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTerceiraFileiraLayout.createSequentialGroup()
                        .addGroup(jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRua)
                            .addComponent(jLabelNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTerceiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        jLabelSearchPacienteIcon.setBackground(new java.awt.Color(255, 0, 51));
        jLabelSearchPacienteIcon.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSearchPacienteIcon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchPacienteIcon.setText("Salvar");
        jLabelSearchPacienteIcon.setBorder(new javax.swing.border.MatteBorder(null));
        jLabelSearchPacienteIcon.setPreferredSize(new java.awt.Dimension(220, 24));
        jLabelSearchPacienteIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelSearchPacienteIconActionPerformed(evt);
            }
        });

        jPanelQuartaFileira.setBackground(new java.awt.Color(185, 244, 115));
        jPanelQuartaFileira.setPreferredSize(new java.awt.Dimension(1440, 104));

        jPanelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jPanelEmail.setPreferredSize(new java.awt.Dimension(226, 24));
        jPanelEmail.setVerifyInputWhenFocusTarget(false);

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setBorder(null);

        javax.swing.GroupLayout jPanelEmailLayout = new javax.swing.GroupLayout(jPanelEmail);
        jPanelEmail.setLayout(jPanelEmailLayout);
        jPanelEmailLayout.setHorizontalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        jPanelEmailLayout.setVerticalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email*");

        jPanelSenha.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jPasswordFieldSenha.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldSenha.setBorder(null);

        javax.swing.GroupLayout jPanelSenhaLayout = new javax.swing.GroupLayout(jPanelSenha);
        jPanelSenha.setLayout(jPanelSenhaLayout);
        jPanelSenhaLayout.setHorizontalGroup(
            jPanelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelSenhaLayout.setVerticalGroup(
            jPanelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha*");

        javax.swing.GroupLayout jPanelQuartaFileiraLayout = new javax.swing.GroupLayout(jPanelQuartaFileira);
        jPanelQuartaFileira.setLayout(jPanelQuartaFileiraLayout);
        jPanelQuartaFileiraLayout.setHorizontalGroup(
            jPanelQuartaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuartaFileiraLayout.createSequentialGroup()
                .addGroup(jPanelQuartaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuartaFileiraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEmail))
                    .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelQuartaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelQuartaFileiraLayout.setVerticalGroup(
            jPanelQuartaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuartaFileiraLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelQuartaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelQuartaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelSegundaFileira.setBackground(new java.awt.Color(185, 244, 115));
        jPanelSegundaFileira.setPreferredSize(new java.awt.Dimension(1440, 104));

        jPanelCEP.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCEP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jFormattedTextFieldCEP.setBorder(null);
        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldCEP.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelCEPLayout = new javax.swing.GroupLayout(jPanelCEP);
        jPanelCEP.setLayout(jPanelCEPLayout);
        jPanelCEPLayout.setHorizontalGroup(
            jPanelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelCEPLayout.setVerticalGroup(
            jPanelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabelCEP.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCEP.setText("CEP");

        jPanelEstado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldEstado.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEstado.setToolTipText("Digite A Sigla Do Estado");
        jTextFieldEstado.setBorder(null);

        javax.swing.GroupLayout jPanelEstadoLayout = new javax.swing.GroupLayout(jPanelEstado);
        jPanelEstado.setLayout(jPanelEstadoLayout);
        jPanelEstadoLayout.setHorizontalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelEstadoLayout.setVerticalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel13.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado");

        jPanelMunicipio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMunicipio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldMunicipio.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldMunicipio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMunicipio.setBorder(null);
        jTextFieldMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMunicipioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMunicipioLayout = new javax.swing.GroupLayout(jPanelMunicipio);
        jPanelMunicipio.setLayout(jPanelMunicipioLayout);
        jPanelMunicipioLayout.setHorizontalGroup(
            jPanelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelMunicipioLayout.setVerticalGroup(
            jPanelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldMunicipio)
        );

        jLabel14.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Município");

        javax.swing.GroupLayout jPanelSegundaFileiraLayout = new javax.swing.GroupLayout(jPanelSegundaFileira);
        jPanelSegundaFileira.setLayout(jPanelSegundaFileiraLayout);
        jPanelSegundaFileiraLayout.setHorizontalGroup(
            jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegundaFileiraLayout.createSequentialGroup()
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSegundaFileiraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCEP)))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSegundaFileiraLayout.setVerticalGroup(
            jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegundaFileiraLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCEP)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSegundaFileira, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrimeiraFileira, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTerceiraFileira, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelQuartaFileira, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabelSearchPacienteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrimeiraFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSegundaFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTerceiraFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelQuartaFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSearchPacienteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 30)); // NOI18N
        jLabelTitulo.setText("Laboratorio");

        jPanelInfo.setBackground(new java.awt.Color(185, 244, 115));

        jLabelNome1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelNome1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTipoAcesso.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelTipoAcesso.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addComponent(jLabelNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTipoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        jPanelInfoHide.setBackground(new java.awt.Color(185, 244, 115));

        javax.swing.GroupLayout jPanelInfoHideLayout = new javax.swing.GroupLayout(jPanelInfoHide);
        jPanelInfoHide.setLayout(jPanelInfoHideLayout);
        jPanelInfoHideLayout.setHorizontalGroup(
            jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInfoHideLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabelIDHide)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );
        jPanelInfoHideLayout.setVerticalGroup(
            jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
            .addGroup(jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInfoHideLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabelIDHide)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(86, 230, 44));
        jPanel1.setForeground(new java.awt.Color(86, 230, 44));

        tab1.setBackground(new java.awt.Color(0, 153, 153));
        tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Exame");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        tab2.setBackground(new java.awt.Color(0, 153, 153));
        tab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Paciente");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab3.setBackground(new java.awt.Color(0, 153, 153));
        tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Médico");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab4.setBackground(new java.awt.Color(0, 153, 153));
        tab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Laboratório");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VITAMED");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        tab5.setBackground(new java.awt.Color(0, 153, 153));
        tab5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Sair");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\tanig\\Downloads\\icons8-sair-50.png")); // NOI18N

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(59, 59, 59)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5)))
                .addContainerGap(129, Short.MAX_VALUE))
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(806, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGeralLayout = new javax.swing.GroupLayout(jPanelGeral);
        jPanelGeral.setLayout(jPanelGeralLayout);
        jPanelGeralLayout.setHorizontalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelGeralLayout.createSequentialGroup()
                            .addComponent(jPanelInfoHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(999, Short.MAX_VALUE))
        );
        jPanelGeralLayout.setVerticalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInfoHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSearchPacienteIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelSearchPacienteIconActionPerformed
        // TODO add your handling code here:
        String teste = jFormattedTextFieldCNPJ.getText();
        if (!jTextFieldNome.getText().equals("")
                && !jFormattedTextFieldCNPJ.getText().equals("  .   .   /    -  ")
                && !jTextFieldEmail.getText().equals("")
                && jPasswordFieldSenha.getPassword().length > 0) {
            jPanelNome.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).top,
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).left,
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).bottom,
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).right)));

            jPanelNome.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).top,
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).left,
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).bottom,
                            jPanelNome.getBorder().getBorderInsets(jPanelNome).right)));

            jPanelCNPJ.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).top,
                            jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).left,
                            jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).bottom,
                            jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).right)));

            jPanelEmail.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).top,
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).left,
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).bottom,
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).right)));

            jPanelSenha.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).top,
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).left,
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).bottom,
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).right)));

            Laboratorio laboratorio = new Laboratorio();
            laboratorio.setNome(jTextFieldNome.getText());
            laboratorio.setCnpj(jFormattedTextFieldCNPJ.getText());
            laboratorio.setTelefone(jFormattedTextFieldTelefone.getText());
            laboratorio.setCep(jFormattedTextFieldCEP.getText());
            laboratorio.setEstado(jTextFieldEstado.getText());
            laboratorio.setCidade(jTextFieldMunicipio.getText());
            laboratorio.setBairro(jTextFieldBairro.getText());
            laboratorio.setRua(jTextRua.getText());
            laboratorio.setNumero(Integer.parseInt(jFormattedTextFieldNumero.getText()));
            laboratorio.setEmail(jTextFieldEmail.getText());
            laboratorio.setStatus_(true);
            laboratorio.setSenha(String.valueOf(jPasswordFieldSenha.getPassword()));
            laboratorio.setTipoAcesso("Laboratorio");

            if (!laboratorio.verificarEmailExistente(jTextFieldEmail.getText())) {
                if (laboratorio.cadastraLaboratorio()) {
                    JOptionPane.showMessageDialog(null, "Laboratorio Cadastrado Com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    new TelaLaboratorio(jLabelIDHide.getText(), jLabelNome1.getText(), jLabelTipoAcesso.getText()).setVisible(true); // Open the Second.java window
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "E-mail Já Cadastrado",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            if (jTextFieldNome.getText().equals("")) {
                jPanelNome.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).top,
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).left,
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).bottom,
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).right)));
            } else if (!jTextFieldNome.getText().equals("")) {
                jPanelNome.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).top,
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).left,
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).bottom,
                                jPanelNome.getBorder().getBorderInsets(jPanelNome).right)));
            }

            if (jFormattedTextFieldCNPJ.getText().equals("  .   .   /    -  ")) {
                jPanelCNPJ.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).top,
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).left,
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).bottom,
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).right)));
            } else if (!jFormattedTextFieldCNPJ.getText().equals("  .   .   /    -  ")) {
                jPanelCNPJ.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).top,
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).left,
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).bottom,
                                jPanelCNPJ.getBorder().getBorderInsets(jPanelCNPJ).right)));
            }

            if (jTextFieldEmail.getText().equals("")) {
                jPanelEmail.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).top,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).left,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).bottom,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).right)));
            } else if (!jTextFieldEmail.getText().equals("")) {
                jPanelEmail.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).top,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).left,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).bottom,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).right)));
            }

            if (jPasswordFieldSenha.getPassword().length == 0) {
                jPanelSenha.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).top,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).left,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).bottom,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).right)));
            } else if (jPasswordFieldSenha.getPassword().length > 0) {
                jPanelSenha.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).top,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).left,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).bottom,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).right)));
            }

            JOptionPane.showMessageDialog(null, "Preencha Os Campos Obrigatórios",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelSearchPacienteIconActionPerformed

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked

        new TelaExame(jLabelIDHide.getText(),jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true); // Open the Second.java window
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        new TelaPaciente(jLabelIDHide.getText(),jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true); // Open the Second.java window
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        new TelaMedico(jLabelIDHide.getText(),jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        new TelaLaboratorio(jLabelIDHide.getText(),jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        new TelaLogin().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_tab5MouseClicked

    private void jTextFieldMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLaboratorio_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLaboratorio_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLaboratorio_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLaboratorio_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLaboratorio_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumero;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCNPJ;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIDHide;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JButton jLabelSearchPacienteIcon;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTipoAcesso;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBairro;
    private javax.swing.JPanel jPanelCEP;
    private javax.swing.JPanel jPanelCNPJ;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoHide;
    private javax.swing.JPanel jPanelMunicipio;
    private javax.swing.JPanel jPanelNome;
    private javax.swing.JPanel jPanelNumero;
    private javax.swing.JPanel jPanelPrimeiraFileira;
    private javax.swing.JPanel jPanelQuartaFileira;
    private javax.swing.JPanel jPanelRua;
    private javax.swing.JPanel jPanelSegundaFileira;
    private javax.swing.JPanel jPanelSenha;
    private javax.swing.JPanel jPanelTelefone;
    private javax.swing.JPanel jPanelTerceiraFileira;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldMunicipio;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextRua;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    // End of variables declaration//GEN-END:variables
}
