/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telasa3;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author tanig
 */
public class TelaExame_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaExame_Cadastro
     */
    public TelaExame_Cadastro() {
        initComponents();
    }

    public TelaExame_Cadastro(String id, String nome, String tipoAcesso) {
        initComponents();
        jLabelIDHide.setText(id);
        jLabelNome.setText(nome);
        jLabelTipoAcesso.setText(tipoAcesso);
        jPanelInfoHide.setVisible(false);
        
        visibilidadeMenu();
    }
    
     public void visibilidadeMenu() {
        if (jLabelTipoAcesso.getText().equals("Paciente")) {
            tab2.setVisible(true);
            tab2.setVisible(false);
            tab3.setVisible(false);
            tab4.setVisible(false);
        } else if (jLabelTipoAcesso.getText().equals("Medico")) {
            tab2.setVisible(true);
            tab2.setVisible(true);
            tab3.setVisible(false);
            tab4.setVisible(false);
        } else if (jLabelTipoAcesso.getText().equals("Laboratorio")) {
            tab2.setVisible(true);
            tab2.setVisible(true);
            tab3.setVisible(false);
            tab4.setVisible(false);
        } else {
            tab2.setVisible(true);
            tab2.setVisible(true);
            tab3.setVisible(true);
            tab4.setVisible(true);
        }
    }

    private List<Paciente> Pacientes;
    private Paciente paciente;
    private Laboratorio laboratorio;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tab5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jPanelPrimeiraFileira = new javax.swing.JPanel();
        jPanelPaciente = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelLaboratorio = new javax.swing.JPanel();
        jFormattedTextFieldLaboratorio = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelHemacias = new javax.swing.JPanel();
        jTextHemacias = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanelHematocrito = new javax.swing.JPanel();
        jTextFieldHematocrito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanelHemoglobina = new javax.swing.JPanel();
        jTextHemaglobina = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanelVolumeGlobular = new javax.swing.JPanel();
        jTextFieldVolumeGlobular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanelSegundaFileira = new javax.swing.JPanel();
        jPanelLeucocitos = new javax.swing.JPanel();
        jTextFieldLeucocitos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanelPlaquetas = new javax.swing.JPanel();
        jTextFieldPlaquetas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanelObservacao = new javax.swing.JPanel();
        jTextObservacao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanelDataCriacao = new javax.swing.JPanel();
        jFormattedTextFieldDataCriacao = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanelResponsavel = new javax.swing.JPanel();
        jTextResponsavel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanelCodigoExame = new javax.swing.JPanel();
        jTextFieldCodigoExame = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabelSearchPacienteIcon = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelTipoAcesso = new javax.swing.JLabel();
        jPanelInfoHide = new javax.swing.JPanel();
        jLabelIDHide = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeral.setBackground(new java.awt.Color(185, 244, 115));

        jPanel1.setBackground(new java.awt.Color(86, 230, 44));
        jPanel1.setForeground(new java.awt.Color(86, 230, 44));

        tab1.setBackground(new java.awt.Color(0, 153, 153));
        tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Exame");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        tab2.setBackground(new java.awt.Color(0, 153, 153));
        tab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Paciente");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab3.setBackground(new java.awt.Color(0, 153, 153));
        tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Médico");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab4.setBackground(new java.awt.Color(0, 153, 153));
        tab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Laboratório");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VITAMED");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        tab5.setBackground(new java.awt.Color(0, 153, 153));
        tab5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Sair");

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\tanig\\Downloads\\icons8-sair-50.png")); // NOI18N

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGroup(tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelForm.setBackground(new java.awt.Color(185, 244, 115));
        jPanelForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        jPanelPrimeiraFileira.setBackground(new java.awt.Color(185, 244, 115));
        jPanelPrimeiraFileira.setPreferredSize(new java.awt.Dimension(1440, 104));

        jPanelPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jPanelPaciente.setPreferredSize(new java.awt.Dimension(226, 24));
        jPanelPaciente.setVerifyInputWhenFocusTarget(false);

        jFormattedTextField1.setBorder(null);
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelPacienteLayout = new javax.swing.GroupLayout(jPanelPaciente);
        jPanelPaciente.setLayout(jPanelPacienteLayout);
        jPanelPacienteLayout.setHorizontalGroup(
            jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelPacienteLayout.setVerticalGroup(
            jPanelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CPF Paciente*");

        jPanelLaboratorio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLaboratorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jFormattedTextFieldLaboratorio.setBorder(null);
        try {
            jFormattedTextFieldLaboratorio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldLaboratorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldLaboratorio.setToolTipText("Digite O CNPJ Do Laboratório");
        jFormattedTextFieldLaboratorio.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelLaboratorioLayout = new javax.swing.GroupLayout(jPanelLaboratorio);
        jPanelLaboratorio.setLayout(jPanelLaboratorioLayout);
        jPanelLaboratorioLayout.setHorizontalGroup(
            jPanelLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelLaboratorioLayout.setVerticalGroup(
            jPanelLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldLaboratorio)
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Laboratório*");

        jPanelHemacias.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHemacias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jPanelHemacias.setPreferredSize(new java.awt.Dimension(226, 24));

        jTextHemacias.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextHemacias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextHemacias.setBorder(null);

        javax.swing.GroupLayout jPanelHemaciasLayout = new javax.swing.GroupLayout(jPanelHemacias);
        jPanelHemacias.setLayout(jPanelHemaciasLayout);
        jPanelHemaciasLayout.setHorizontalGroup(
            jPanelHemaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextHemacias, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelHemaciasLayout.setVerticalGroup(
            jPanelHemaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextHemacias, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hemacias");

        jPanelHematocrito.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHematocrito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldHematocrito.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldHematocrito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHematocrito.setBorder(null);

        javax.swing.GroupLayout jPanelHematocritoLayout = new javax.swing.GroupLayout(jPanelHematocrito);
        jPanelHematocrito.setLayout(jPanelHematocritoLayout);
        jPanelHematocritoLayout.setHorizontalGroup(
            jPanelHematocritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldHematocrito, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelHematocritoLayout.setVerticalGroup(
            jPanelHematocritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldHematocrito)
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hematocrito");

        jPanelHemoglobina.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHemoglobina.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextHemaglobina.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextHemaglobina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextHemaglobina.setBorder(null);

        javax.swing.GroupLayout jPanelHemoglobinaLayout = new javax.swing.GroupLayout(jPanelHemoglobina);
        jPanelHemoglobina.setLayout(jPanelHemoglobinaLayout);
        jPanelHemoglobinaLayout.setHorizontalGroup(
            jPanelHemoglobinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextHemaglobina, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelHemoglobinaLayout.setVerticalGroup(
            jPanelHemoglobinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextHemaglobina)
        );

        jLabel10.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hemoglobina");

        jPanelVolumeGlobular.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVolumeGlobular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldVolumeGlobular.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldVolumeGlobular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVolumeGlobular.setBorder(null);

        javax.swing.GroupLayout jPanelVolumeGlobularLayout = new javax.swing.GroupLayout(jPanelVolumeGlobular);
        jPanelVolumeGlobular.setLayout(jPanelVolumeGlobularLayout);
        jPanelVolumeGlobularLayout.setHorizontalGroup(
            jPanelVolumeGlobularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldVolumeGlobular, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelVolumeGlobularLayout.setVerticalGroup(
            jPanelVolumeGlobularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldVolumeGlobular)
        );

        jLabel11.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Volume Globular");

        javax.swing.GroupLayout jPanelPrimeiraFileiraLayout = new javax.swing.GroupLayout(jPanelPrimeiraFileira);
        jPanelPrimeiraFileira.setLayout(jPanelPrimeiraFileiraLayout);
        jPanelPrimeiraFileiraLayout.setHorizontalGroup(
            jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimeiraFileiraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jPanelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHemacias, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHematocrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHemoglobina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVolumeGlobular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanelPrimeiraFileiraLayout.setVerticalGroup(
            jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrimeiraFileiraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelPrimeiraFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelVolumeGlobular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHemoglobina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHematocrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jPanelHemacias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelSegundaFileira.setBackground(new java.awt.Color(185, 244, 115));
        jPanelSegundaFileira.setPreferredSize(new java.awt.Dimension(1440, 104));

        jPanelLeucocitos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLeucocitos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldLeucocitos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldLeucocitos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLeucocitos.setBorder(null);

        javax.swing.GroupLayout jPanelLeucocitosLayout = new javax.swing.GroupLayout(jPanelLeucocitos);
        jPanelLeucocitos.setLayout(jPanelLeucocitosLayout);
        jPanelLeucocitosLayout.setHorizontalGroup(
            jPanelLeucocitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldLeucocitos, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelLeucocitosLayout.setVerticalGroup(
            jPanelLeucocitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldLeucocitos)
        );

        jLabel12.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Leucocitos");

        jPanelPlaquetas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPlaquetas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldPlaquetas.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldPlaquetas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPlaquetas.setBorder(null);

        javax.swing.GroupLayout jPanelPlaquetasLayout = new javax.swing.GroupLayout(jPanelPlaquetas);
        jPanelPlaquetas.setLayout(jPanelPlaquetasLayout);
        jPanelPlaquetasLayout.setHorizontalGroup(
            jPanelPlaquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldPlaquetas, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelPlaquetasLayout.setVerticalGroup(
            jPanelPlaquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldPlaquetas)
        );

        jLabel13.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Plaquetas");

        jPanelObservacao.setBackground(new java.awt.Color(255, 255, 255));
        jPanelObservacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextObservacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextObservacao.setBorder(null);

        javax.swing.GroupLayout jPanelObservacaoLayout = new javax.swing.GroupLayout(jPanelObservacao);
        jPanelObservacao.setLayout(jPanelObservacaoLayout);
        jPanelObservacaoLayout.setHorizontalGroup(
            jPanelObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        jPanelObservacaoLayout.setVerticalGroup(
            jPanelObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextObservacao)
        );

        jLabel14.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Observação");

        jPanelDataCriacao.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDataCriacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jFormattedTextFieldDataCriacao.setBorder(null);
        try {
            jFormattedTextFieldDataCriacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataCriacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldDataCriacao.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanelDataCriacaoLayout = new javax.swing.GroupLayout(jPanelDataCriacao);
        jPanelDataCriacao.setLayout(jPanelDataCriacaoLayout);
        jPanelDataCriacaoLayout.setHorizontalGroup(
            jPanelDataCriacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldDataCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelDataCriacaoLayout.setVerticalGroup(
            jPanelDataCriacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFormattedTextFieldDataCriacao)
        );

        jLabel15.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data Criação");

        jPanelResponsavel.setBackground(new java.awt.Color(255, 255, 255));
        jPanelResponsavel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextResponsavel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextResponsavel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextResponsavel.setBorder(null);
        jTextResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextResponsavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelResponsavelLayout = new javax.swing.GroupLayout(jPanelResponsavel);
        jPanelResponsavel.setLayout(jPanelResponsavelLayout);
        jPanelResponsavelLayout.setHorizontalGroup(
            jPanelResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelResponsavelLayout.setVerticalGroup(
            jPanelResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextResponsavel)
        );

        jLabel16.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Responsável");

        jPanelCodigoExame.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCodigoExame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jTextFieldCodigoExame.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldCodigoExame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoExame.setBorder(null);

        javax.swing.GroupLayout jPanelCodigoExameLayout = new javax.swing.GroupLayout(jPanelCodigoExame);
        jPanelCodigoExame.setLayout(jPanelCodigoExameLayout);
        jPanelCodigoExameLayout.setHorizontalGroup(
            jPanelCodigoExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCodigoExame, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanelCodigoExameLayout.setVerticalGroup(
            jPanelCodigoExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCodigoExame, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Código Exame*");

        javax.swing.GroupLayout jPanelSegundaFileiraLayout = new javax.swing.GroupLayout(jPanelSegundaFileira);
        jPanelSegundaFileira.setLayout(jPanelSegundaFileiraLayout);
        jPanelSegundaFileiraLayout.setHorizontalGroup(
            jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSegundaFileiraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jPanelLeucocitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPlaquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jPanelResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jPanelCodigoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanelSegundaFileiraLayout.setVerticalGroup(
            jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSegundaFileiraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelSegundaFileiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCodigoExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLeucocitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDataCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPlaquetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelSearchPacienteIcon.setBackground(new java.awt.Color(255, 0, 51));
        jLabelSearchPacienteIcon.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSearchPacienteIcon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchPacienteIcon.setText("Salvar");
        jLabelSearchPacienteIcon.setBorder(new javax.swing.border.MatteBorder(null));
        jLabelSearchPacienteIcon.setPreferredSize(new java.awt.Dimension(220, 24));
        jLabelSearchPacienteIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelSearchPacienteIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelSegundaFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelPrimeiraFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(jLabelSearchPacienteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrimeiraFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSegundaFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSearchPacienteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(586, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 30)); // NOI18N
        jLabelTitulo.setText("Exame De Sangue");

        jPanelInfo.setBackground(new java.awt.Color(185, 244, 115));

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTipoAcesso.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelTipoAcesso.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addComponent(jLabelTipoAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addGap(66, 66, 66))))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTipoAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelInfoHide.setBackground(new java.awt.Color(185, 244, 115));

        javax.swing.GroupLayout jPanelInfoHideLayout = new javax.swing.GroupLayout(jPanelInfoHide);
        jPanelInfoHide.setLayout(jPanelInfoHideLayout);
        jPanelInfoHideLayout.setHorizontalGroup(
            jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInfoHideLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabelIDHide)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );
        jPanelInfoHideLayout.setVerticalGroup(
            jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
            .addGroup(jPanelInfoHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInfoHideLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabelIDHide)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelGeralLayout = new javax.swing.GroupLayout(jPanelGeral);
        jPanelGeral.setLayout(jPanelGeralLayout);
        jPanelGeralLayout.setHorizontalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGeralLayout.createSequentialGroup()
                                .addGap(602, 602, 602)
                                .addComponent(jLabelTitulo))
                            .addComponent(jPanelInfoHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelGeralLayout.setVerticalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addComponent(jPanelInfoHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        new TelaExame(jLabelIDHide.getText(), jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true); // Open the Second.java window
        dispose();
    }//GEN-LAST:event_tab1MouseClicked

    private void jTextResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextResponsavelActionPerformed

    private void jLabelSearchPacienteIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelSearchPacienteIconActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldCodigoExame.getText().equals("")
                && !jFormattedTextField1.getText().equals("   .   .   -  ")
                && !jFormattedTextFieldLaboratorio.getText().equals("  .   .   /    -  ")) {
            jPanelCodigoExame.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).top,
                            jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).left,
                            jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).bottom,
                            jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).right)));

            jPanelPaciente.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).top,
                            jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).left,
                            jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).bottom,
                            jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).right)));

            jPanelLaboratorio.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).top,
                            jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).left,
                            jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).bottom,
                            jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).right)));

            Paciente pacienteQuery = new Paciente();
            this.paciente = pacienteQuery.consultaPaciente(jFormattedTextField1.getText());
            Laboratorio laboratorioQuery = new Laboratorio();
            this.laboratorio = laboratorioQuery.consultaLaboratorio(jFormattedTextFieldLaboratorio.getText());
            Exame_Sangue exame = new Exame_Sangue();
            exame.setPacienteID(this.paciente.getPacienteID());
            exame.setLaboratorioID(this.laboratorio.getLaboratorioID());
            exame.setHemacias(Integer.parseInt(jTextHemacias.getText()));
            exame.setHematocrito(Integer.parseInt(jTextFieldHematocrito.getText()));
            exame.setHemoglobinas(Integer.parseInt(jTextHemaglobina.getText()));
            exame.setVolumeGlobularMedio(Integer.parseInt(jTextFieldVolumeGlobular.getText()));
            exame.setCodigoExame(Integer.parseInt(jTextFieldCodigoExame.getText()));
            exame.setLeucocitos(Integer.parseInt(jTextFieldLeucocitos.getText()));
            exame.setPlaquetas(Integer.parseInt(jTextFieldPlaquetas.getText()));
            exame.setObservacao(jTextObservacao.getText());
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String data = jFormattedTextFieldDataCriacao.getText();
            try {
                Date date = formatter.parse(data);
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                exame.setDataCriacao(sqlDate);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            exame.setResponsavelCriacao(jTextResponsavel.getText());
            exame.setCodigoExame(Integer.parseInt(jTextFieldCodigoExame.getText()));
            if (exame.cadastraExame()) {
                JOptionPane.showMessageDialog(null, "Exame Cadastrado Com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                new TelaExame(jLabelIDHide.getText(), jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true); // Open the Second.java window
                dispose();
            }
        } else {
            if (jTextFieldCodigoExame.getText().equals("")) {
                jPanelCodigoExame.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).top,
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).left,
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).bottom,
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).right)));
            } else if (!jTextFieldCodigoExame.getText().equals("")) {
                jPanelCodigoExame.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).top,
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).left,
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).bottom,
                                jPanelCodigoExame.getBorder().getBorderInsets(jPanelCodigoExame).right)));
            }

            if (jFormattedTextField1.getText().equals("   .   .   -  ")) {
                jPanelPaciente.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).top,
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).left,
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).bottom,
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).right)));
            } else if (!jFormattedTextField1.getText().equals("   .   .   -  ")) {
                jPanelPaciente.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).top,
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).left,
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).bottom,
                                jPanelPaciente.getBorder().getBorderInsets(jPanelPaciente).right)));
            }

            if (jFormattedTextFieldLaboratorio.getText().equals("  .   .   /    -  ")) {
                jPanelLaboratorio.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).top,
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).left,
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).bottom,
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).right)));
            } else if (!jFormattedTextFieldLaboratorio.getText().equals("  .   .   /    -  ")) {
                jPanelLaboratorio.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).top,
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).left,
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).bottom,
                                jPanelLaboratorio.getBorder().getBorderInsets(jPanelLaboratorio).right)));
            }

            JOptionPane.showMessageDialog(null, "Preencha Os Campos Obrigatórios",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jLabelSearchPacienteIconActionPerformed

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        new TelaPaciente(jLabelIDHide.getText(), jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true); // Open the Second.java window
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        new TelaMedico(jLabelIDHide.getText(), jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        new TelaLaboratorio(jLabelIDHide.getText(), jLabelNome.getText(), jLabelTipoAcesso.getText()).setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        new TelaLogin().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_tab5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExame_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExame_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExame_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExame_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExame_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCriacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldLaboratorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIDHide;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JButton jLabelSearchPacienteIcon;
    private javax.swing.JLabel jLabelTipoAcesso;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCodigoExame;
    private javax.swing.JPanel jPanelDataCriacao;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelHemacias;
    private javax.swing.JPanel jPanelHematocrito;
    private javax.swing.JPanel jPanelHemoglobina;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoHide;
    private javax.swing.JPanel jPanelLaboratorio;
    private javax.swing.JPanel jPanelLeucocitos;
    private javax.swing.JPanel jPanelObservacao;
    private javax.swing.JPanel jPanelPaciente;
    private javax.swing.JPanel jPanelPlaquetas;
    private javax.swing.JPanel jPanelPrimeiraFileira;
    private javax.swing.JPanel jPanelResponsavel;
    private javax.swing.JPanel jPanelSegundaFileira;
    private javax.swing.JPanel jPanelVolumeGlobular;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCodigoExame;
    private javax.swing.JTextField jTextFieldHematocrito;
    private javax.swing.JTextField jTextFieldLeucocitos;
    private javax.swing.JTextField jTextFieldPlaquetas;
    private javax.swing.JTextField jTextFieldVolumeGlobular;
    private javax.swing.JTextField jTextHemacias;
    private javax.swing.JTextField jTextHemaglobina;
    private javax.swing.JTextField jTextObservacao;
    private javax.swing.JTextField jTextResponsavel;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pacientes
     */
    public List<Paciente> getPacientes() {
        return Pacientes;
    }

    /**
     * @param pacientes the pacientes to set
     */
    public void setPacientes(List<Paciente> pacientes) {
        this.Pacientes = pacientes;
    }
}
