/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telasa3;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author tanig
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeral = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelForm = new javax.swing.JPanel();
        jPanelEmail = new javax.swing.JPanel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jPanelSenha = new javax.swing.JPanel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jLabelSearchPacienteIcon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeral.setBackground(new java.awt.Color(185, 244, 115));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\tanig\\Downloads\\telasA3\\src\\main\\java\\com\\mycompany\\telasa3\\8666781_activity_health_icon.png")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel7.setText("VITAMED");

        jPanelForm.setBackground(new java.awt.Color(185, 244, 115));

        jPanelEmail.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jPanelEmail.setPreferredSize(new java.awt.Dimension(226, 24));
        jPanelEmail.setVerifyInputWhenFocusTarget(false);

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setBorder(null);

        javax.swing.GroupLayout jPanelEmailLayout = new javax.swing.GroupLayout(jPanelEmail);
        jPanelEmail.setLayout(jPanelEmailLayout);
        jPanelEmailLayout.setHorizontalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        jPanelEmailLayout.setVerticalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email*");

        jPanelSenha.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jPasswordFieldSenha.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldSenha.setBorder(null);

        javax.swing.GroupLayout jPanelSenhaLayout = new javax.swing.GroupLayout(jPanelSenha);
        jPanelSenha.setLayout(jPanelSenhaLayout);
        jPanelSenhaLayout.setHorizontalGroup(
            jPanelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPasswordFieldSenha)
        );
        jPanelSenhaLayout.setVerticalGroup(
            jPanelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha*");

        jLabelSearchPacienteIcon.setBackground(new java.awt.Color(255, 0, 51));
        jLabelSearchPacienteIcon.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSearchPacienteIcon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchPacienteIcon.setText("Entrar");
        jLabelSearchPacienteIcon.setBorder(new javax.swing.border.MatteBorder(null));
        jLabelSearchPacienteIcon.setPreferredSize(new java.awt.Dimension(220, 24));
        jLabelSearchPacienteIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelSearchPacienteIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
        jPanelForm.setLayout(jPanelFormLayout);
        jPanelFormLayout.setHorizontalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelSearchPacienteIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(jLabelSenha, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanelFormLayout.setVerticalGroup(
            jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelSearchPacienteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGeralLayout = new javax.swing.GroupLayout(jPanelGeral);
        jPanelGeral.setLayout(jPanelGeralLayout);
        jPanelGeralLayout.setHorizontalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addContainerGap(1107, Short.MAX_VALUE)
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeralLayout.createSequentialGroup()
                        .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(681, 681, 681))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeralLayout.createSequentialGroup()
                        .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(847, 847, 847))))
        );
        jPanelGeralLayout.setVerticalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSearchPacienteIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelSearchPacienteIconActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldEmail.getText().equals("")
                && jPasswordFieldSenha.getPassword().length > 0) {

            jPanelEmail.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).top,
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).left,
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).bottom,
                            jPanelEmail.getBorder().getBorderInsets(jPanelEmail).right)));

            jPanelSenha.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                            Color.BLACK, Color.BLACK, Color.BLACK),
                    BorderFactory.createEmptyBorder(
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).top,
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).left,
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).bottom,
                            jPanelSenha.getBorder().getBorderInsets(jPanelSenha).right)));

            Acesso acesso = new Acesso();
            acesso.setEmail(jTextFieldEmail.getText());
            acesso.setSenha(String.valueOf(jPasswordFieldSenha.getPassword()));
            if (acesso.verificarAcesso() != null) {
                new TelaHome(acesso.verificarAcesso()).setVisible(true); // Open the Second.java window
                dispose(); // Close the First.java window
            } else {
                JOptionPane.showMessageDialog(null, "E mail ou Senha Incorretos",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                jTextFieldEmail.setText("");
                jPasswordFieldSenha.setText("");

            }

        } else {
            if (jTextFieldEmail.getText().equals("")) {
                jPanelEmail.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).top,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).left,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).bottom,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).right)));
            } else if (!jTextFieldEmail.getText().equals("")) {
                jPanelEmail.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).top,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).left,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).bottom,
                                jPanelEmail.getBorder().getBorderInsets(jPanelEmail).right)));
            }

            if (jPasswordFieldSenha.getPassword().length == 0) {
                jPanelSenha.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.RED,
                                Color.RED, Color.RED, Color.RED),
                        BorderFactory.createEmptyBorder(
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).top,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).left,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).bottom,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).right)));
            } else if (jPasswordFieldSenha.getPassword().length > 0) {
                jPanelSenha.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createSoftBevelBorder(BevelBorder.LOWERED, Color.BLACK,
                                Color.BLACK, Color.BLACK, Color.BLACK),
                        BorderFactory.createEmptyBorder(
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).top,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).left,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).bottom,
                                jPanelSenha.getBorder().getBorderInsets(jPanelSenha).right)));
            }

            JOptionPane.showMessageDialog(null, "Preencha Os Campos Obrigatórios",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelSearchPacienteIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JButton jLabelSearchPacienteIcon;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
